require("dotenv").config();
const mongoose = require("mongoose");
const Place = require("../models/Place.model");

const imageMap = {
  'taj-mahal': 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80&w=1080',
  'jaipur-palace': 'https://plus.unsplash.com/premium_photo-1661963054563-ce928e477ff3?q=80&w=2070&auto=format&fit=crop',
  'hampi-ruins': 'https://images.unsplash.com/photo-1616606484004-5ef3cc46e39d?q=80&w=2070&auto=format&fit=crop',
  'ajanta-caves': 'https://images.unsplash.com/photo-1649052894514-7c287bd147e8?auto=format&fit=crop&q=80&w=1080',
  'qutub-minar': 'https://images.unsplash.com/photo-1667849521212-e9843b89f322?q=80&w=3270&auto=format&fit=crop',
  'mysore-palace': 'https://images.unsplash.com/photo-1600112356915-089abb8fc71a?q=80&w=2494&auto=format&fit=crop',
  'khajuraho': 'https://images.unsplash.com/photo-1606298855672-3efb63017be8?q=80&w=2070&auto=format&fit=crop',
  'jaisalmer-fort': 'https://plus.unsplash.com/premium_photo-1697730388194-0f8f7943dbad?q=80&w=1974&auto=format&fit=crop',
  'ellora-caves': 'https://images.unsplash.com/photo-1572461275348-bf5edc4e4ef9?q=80&w=1035&auto=format&fit=crop',
  'konark-temple': 'https://images.unsplash.com/photo-1677211352662-30e7775c7ce8?q=80&w=2070&auto=format&fit=crop',
  'rani-ki-vav': 'https://images.unsplash.com/photo-1729406617106-796241cbae0b?q=80&w=1974&auto=format&fit=crop',
  'charminar': 'https://images.unsplash.com/photo-1711102230980-5f3001c1a07b?q=80&w=2071&auto=format&fit=crop',
  'mahabalipuram': 'https://plus.unsplash.com/premium_photo-1697729536647-4e23a32dd324?q=80&w=2070&auto=format&fit=crop',
  'victoria-memorial': 'https://images.unsplash.com/photo-1697817665440-f988c6d5080f?q=80&w=1947&auto=format&fit=crop',
  'kerala-backwaters': 'https://images.unsplash.com/photo-1707893013488-51672ef83425?auto=format&fit=crop&q=80&w=1080',
  'valley-of-flowers': 'https://images.unsplash.com/photo-1658939061463-105935bf38cc?q=80&w=2070&auto=format&fit=crop',
  'munnar': 'https://images.unsplash.com/photo-1516690553959-71a414d6b9b6?auto=format&fit=crop&q=80&w=1080',
  'shimla': 'https://images.unsplash.com/photo-1597074866923-dc0589150358?q=80&w=2070&auto=format&fit=crop',
  'cherrapunji': 'https://images.unsplash.com/photo-1552978534-9d01e1f91517?q=80&w=2070&auto=format&fit=crop',
  'darjeeling': 'https://images.unsplash.com/photo-1721140175873-2e664cb286ca?q=80&w=1035&auto=format&fit=crop',
  'udaipur': 'https://plus.unsplash.com/premium_photo-1697729789803-48b0c82365ff?q=80&w=3161&auto=format&fit=crop',
  'golden-temple': 'https://images.unsplash.com/photo-1623059508779-2542c6e83753?auto=format&fit=crop&q=80&w=1080',
  'varanasi-ghats': 'https://images.unsplash.com/photo-1706186839147-0d708602587b?q=80&w=2070&auto=format&fit=crop',
  'meenakshi-temple': 'https://images.unsplash.com/photo-1692173248120-59547c3d4653?auto=format&fit=crop&q=80&w=1080',
  'haridwar': 'https://images.unsplash.com/photo-1511754863001-18d44abd0a93?q=80&w=2070&auto=format&fit=crop',
  'tirupati': 'https://images.unsplash.com/photo-1741003412854-bd4b264c4af3?q=80&w=3132&auto=format&fit=crop',
  'somnath': 'https://images.unsplash.com/photo-1591700430569-9469d38b1006?q=80&w=3128&auto=format&fit=crop',
  'kedarnath': 'https://images.unsplash.com/photo-1623952146070-f13fc902f769?q=80&w=1974&auto=format&fit=crop',
  'bodhgaya': 'https://images.unsplash.com/photo-1667883643074-31b942669d08?q=80&w=2031&auto=format&fit=crop',
  'vaishno-devi': 'https://images.unsplash.com/photo-1717502713522-543a97e13dab?q=80&w=3131&auto=format&fit=crop',
  'ladakh-mountains': 'https://images.unsplash.com/photo-1718679388215-75b00db812f5?auto=format&fit=crop&q=80&w=1080',
  'rishikesh': 'https://plus.unsplash.com/premium_photo-1697730398251-40cd8dc57e0b?q=80&w=2070&auto=format&fit=crop',
  'leh': 'https://images.unsplash.com/photo-1606857090627-27ca46667290?q=80&w=2067&auto=format&fit=crop',
  'spiti': 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&q=80&w=1080',
  'bir-billing': 'https://images.unsplash.com/photo-1620720970374-5b7e67e1e610?q=80&w=2070&auto=format&fit=crop',
  'kaziranga': 'https://images.unsplash.com/photo-1466105350347-d5f1ad709010?q=80&w=2067&auto=format&fit=crop',
  'kaziranga-safari': 'https://images.unsplash.com/photo-1534161308652-fdfcf10f62c4?auto=format&fit=crop&q=80&w=1080',
  'corbett': 'https://plus.unsplash.com/premium_photo-1670959934143-f646ac034d1c?q=80&w=1974&auto=format&fit=crop',
  'sundarbans': 'https://images.unsplash.com/photo-1633453174803-acb1b082f9e3?q=80&w=2070&auto=format&fit=crop',
  'ranthambore': 'https://plus.unsplash.com/premium_photo-1730145749791-28fc538d7203?q=80&w=1035&auto=format&fit=crop',
  'bandhavgarh': 'https://images.unsplash.com/photo-1602491453631-e2a5ad90a131?auto=format&fit=crop&q=80&w=1080',
  'gir': 'https://plus.unsplash.com/premium_photo-1664302797043-869952aeecd3?q=80&w=2364&auto=format&fit=crop',
  'goa-beaches': 'https://plus.unsplash.com/premium_photo-1666286956135-0fb603dad5cf?q=80&w=3131&auto=format&fit=crop',
  'andaman': 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&q=80&w=1080',
  'puri-beach': 'https://images.unsplash.com/photo-1655352710727-6c89536454b3?q=80&w=2960&auto=format&fit=crop',
  'gokarna': 'https://plus.unsplash.com/premium_photo-1664283661436-7b3f6e3416e8?q=80&w=2073&auto=format&fit=crop',
  'varkala': 'https://images.unsplash.com/photo-1697193375091-f9bfe3d7ed7b?q=80&w=2070&auto=format&fit=crop',
  'kutch': 'https://images.unsplash.com/photo-1660733617811-3d905e6c37c4?q=80&w=1480&auto=format&fit=crop',
  'majuli': 'https://images.unsplash.com/photo-1759738103476-9abb3b59458e?q=80&w=2070&auto=format&fit=crop',
  'lonar': 'https://images.unsplash.com/photo-1641035854709-3bc3fe2681e2?q=80&w=2070&auto=format&fit=crop',
  'chitrakote': 'https://portal-tourism.cgstate.gov.in//files/CHITRAKOTE%20Poster%20Image.jpg',
  'sirpur': 'https://images.unsplash.com/photo-1706186843467-f988c6d5080f?q=80&w=1080&auto=format&fit=crop',
  'barnawapara': 'https://images.unsplash.com/photo-1582216654005-cb62494f6c44?q=80&w=1080&auto=format&fit=crop',
  'mainpat': 'https://cdn1.tripoto.com/media/filter/nl/img/2380291/Image/1698404320_img_20220126_012916_2_e1655147843401.jpg.webp'
};

const destinations = [
  {
    id: '1',
    name: 'Taj Mahal',
    city: 'Agra',
    state: 'Uttar Pradesh',
    category: 'Heritage',
    description: 'An ivory-white marble mausoleum on the right bank of the river Yamuna, the Taj Mahal is an iconic symbol of love and one of the Seven Wonders of the World.',
    history: 'Built by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal, the Taj Mahal was constructed between 1632 and 1653.',
    budget: '₹2,000 - ₹5,000 per person',
    latitude: 27.1751,
    longitude: 78.0421,
    images: ['taj-mahal'],
    nearbyAttractions: ['Agra Fort', 'Fatehpur Sikri', 'Mehtab Bagh'],
    rating: 4.9
  },
  {
    id: '2',
    name: 'Kerala Backwaters',
    city: 'Alleppey',
    state: 'Kerala',
    category: 'Nature',
    description: 'A network of interconnected canals, rivers, lakes, and inlets, the Kerala backwaters offer a unique ecosystem and serene beauty.',
    history: 'The backwaters were formed by the action of waves and shore currents creating low barrier islands. Historically used for trade and transport.',
    budget: '₹10,000 - ₹25,000 for houseboat stay',
    latitude: 9.4981,
    longitude: 76.3388,
    images: ['kerala-backwaters'],
    nearbyAttractions: ['Kumarakom', 'Marari Beach', 'Vembanad Lake'],
    rating: 4.8
  },
  {
    id: '3',
    name: 'Golden Temple',
    city: 'Amritsar',
    state: 'Punjab',
    category: 'Spiritual',
    description: 'The holiest Gurdwara and the most important pilgrimage site of Sikhism, known for its stunning golden architecture.',
    history: 'The temple was built in the 16th century by Guru Arjan, the fifth Sikh Guru. The upper floors were covered with gold foil in the early 19th century.',
    budget: '₹1,000 - ₹3,000 per person',
    latitude: 31.62,
    longitude: 74.8765,
    images: ['golden-temple'],
    nearbyAttractions: ['Jallianwala Bagh', 'Wagah Border', 'Partition Museum'],
    rating: 4.9
  },
  {
    id: '4',
    name: 'Ladakh Mountains',
    city: 'Leh',
    state: 'Ladakh',
    category: 'Adventure',
    description: 'A high-altitude desert in the Himalayas, Ladakh offers breathtaking landscapes and ancient monasteries.',
    history: 'Ladakh was historically an important stopover on trade routes along the Indus valley. Influenced by Tibetan Buddhist culture.',
    budget: '₹15,000 - ₹40,000 per week',
    latitude: 34.1526,
    longitude: 77.5771,
    images: ['ladakh-mountains'],
    nearbyAttractions: ['Pangong Lake', 'Nubra Valley', 'Khardung La Pass'],
    rating: 4.8
  },
  {
    id: '5',
    name: 'Jaipur City Palace',
    city: 'Jaipur',
    state: 'Rajasthan',
    category: 'Heritage',
    description: 'A stunning example of Rajput architecture, the City Palace complex includes courtyards and gardens.',
    history: 'Built by Maharaja Sawai Jai Singh II between 1729 and 1732, blends Rajasthani and Mughal architecture.',
    budget: '₹2,500 - ₹6,000 per person',
    latitude: 26.9255,
    longitude: 75.8237,
    images: ['jaipur-palace'],
    nearbyAttractions: ['Hawa Mahal', 'Amber Fort', 'Jantar Mantar'],
    rating: 4.7
  },
  {
    id: '6',
    name: 'Hampi Ruins',
    city: 'Hampi',
    state: 'Karnataka',
    category: 'Heritage',
    description: 'A UNESCO World Heritage Site featuring the ruins of the Vijayanagara Empire across a boulder-strewn landscape.',
    history: 'Hampi was the capital of the Vijayanagara Empire from 1336 to 1565. Renowned for its architectural marvels.',
    budget: '₹3,000 - ₹8,000 per person',
    latitude: 15.335,
    longitude: 76.46,
    images: ['hampi-ruins'],
    nearbyAttractions: ['Virupaksha Temple', 'Vittala Temple', 'Matanga Hill'],
    rating: 4.8
  },
  {
    id: '7',
    name: 'Valley of Flowers',
    city: 'Chamoli',
    state: 'Uttarakhand',
    category: 'Nature',
    description: 'A stunning alpine valley renowned for its meadows of endemic alpine flowers in the Western Himalayas.',
    history: 'Discovered by Frank S. Smythe in 1931, declared a national park in 1982.',
    budget: '₹8,000 - ₹15,000 per trek',
    latitude: 30.7268,
    longitude: 79.6005,
    images: ['valley-of-flowers'],
    nearbyAttractions: ['Hemkund Sahib', 'Badrinath Temple', 'Nanda Devi National Park'],
    rating: 4.9
  },
  {
    id: '8',
    name: 'Varanasi Ghats',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    category: 'Spiritual',
    description: 'The spiritual capital of India, Varanasi\'s ghats along the Ganges offer profound spiritual witness to ancient rituals.',
    history: 'One of the world\'s oldest continuously inhabited cities, sacred to Hindus, Buddhists, and Jains.',
    budget: '₹2,000 - ₹5,000 per person',
    latitude: 25.3176,
    longitude: 82.9739,
    images: ['varanasi-ghats'],
    nearbyAttractions: ['Sarnath', 'Kashi Vishwanath Temple', 'Ramnagar Fort'],
    rating: 4.7
  },
  {
    id: '9',
    name: 'Rishikesh Adventure',
    city: 'Rishikesh',
    state: 'Uttarakhand',
    category: 'Adventure',
    description: 'Known as the adventure capital of India, offering river rafting and yoga/meditation.',
    history: 'A center for spiritual learning and adventure, gained international fame when The Beatles visited in 1968.',
    budget: '₹5,000 - ₹12,000 per person',
    latitude: 30.0869,
    longitude: 78.2676,
    images: ['rishikesh'],
    nearbyAttractions: ['Lakshman Jhula', 'Ram Jhula', 'Triveni Ghat'],
    rating: 4.7
  },
  {
    id: '10',
    name: 'Ajanta Caves',
    city: 'Aurangabad',
    state: 'Maharashtra',
    category: 'Heritage',
    description: 'Rock-cut Buddhist cave monuments dating from the 2nd century BCE, featuring exquisite paintings.',
    history: 'Built in two phases starting from the 2nd century BCE and abandoned around 650 CE. Rediscovered in 1819.',
    budget: '₹3,000 - ₹7,000 per person',
    latitude: 20.552,
    longitude: 75.7033,
    images: ['ajanta-caves'],
    nearbyAttractions: ['Ellora Caves', 'Daulatabad Fort', 'Bibi Ka Maqbara'],
    rating: 4.8
  },
  {
    id: '11',
    name: 'Goa Beaches',
    city: 'Panaji',
    state: 'Goa',
    category: 'Beaches',
    description: 'Known for its pristine beaches, vibrant nightlife, and Portuguese heritage.',
    history: 'Portuguese colony for over 450 years, leaving a lasting influence on architecture and culture.',
    budget: '₹8,000 - ₹20,000 per person',
    latitude: 15.4909,
    longitude: 73.8278,
    images: ['goa-beaches'],
    nearbyAttractions: ['Fort Aguada', 'Basilica of Bom Jesus', 'Dudhsagar Waterfalls'],
    rating: 4.6
  },
  {
    id: '12',
    name: 'Meenakshi Temple',
    city: 'Madurai',
    state: 'Tamil Nadu',
    category: 'Spiritual',
    description: 'A historic Hindu temple dedicated to Goddess Meenakshi, known for its towering gopurams.',
    history: 'Masterpiece of Dravidian architecture, rebuilt between 1623 and 1655 CE.',
    budget: '₹2,000 - ₹4,000 per person',
    latitude: 9.9195,
    longitude: 78.1193,
    images: ['meenakshi-temple'],
    nearbyAttractions: ['Thirumalai Nayakkar Palace', 'Gandhi Memorial Museum', 'Alagar Koil'],
    rating: 4.8
  },
  {
    id: '13',
    name: 'Qutub Minar',
    city: 'Delhi',
    state: 'Delhi',
    category: 'Heritage',
    description: 'A UNESCO World Heritage Site, this 73-meter tall minaret is a masterpiece of Indo-Islamic architecture.',
    history: 'Construction was started by Qutub-ud-din Aibak in 1192. Marks the beginning of Muslim rule in North India.',
    budget: '₹500 - ₹1,500',
    latitude: 28.5245,
    longitude: 77.1855,
    images: ['qutub-minar'],
    nearbyAttractions: ['Mehrauli Archaeological Park', 'Garden of Five Senses'],
    rating: 4.7
  },
  {
    id: '14',
    name: 'Kaziranga National Park',
    city: 'Kanchanjuri',
    state: 'Assam',
    category: 'Wildlife',
    description: 'Home to the world\'s largest population of great one-horned rhinoceroses and a UNESCO site.',
    history: 'Established in 1905, one of the oldest parks in India and a triumph of wildlife conservation.',
    budget: '₹5,000 - ₹12,000',
    latitude: 26.5775,
    longitude: 93.1703,
    images: ['kaziranga'],
    nearbyAttractions: ['Hollongapar Gibbon Sanctuary', 'Tea Gardens'],
    rating: 4.8
  },
  {
    id: '15',
    name: 'Mysore Palace',
    city: 'Mysuru',
    state: 'Karnataka',
    category: 'Heritage',
    description: 'One of the most magnificent buildings in India, former residence of the royal family of Mysore.',
    history: 'Current structure built between 1897 and 1912 after the original wooden palace burned down.',
    budget: '₹1,000 - ₹3,000',
    latitude: 12.3052,
    longitude: 76.6552,
    images: ['mysore-palace'],
    nearbyAttractions: ['Chamundi Hills', 'Brindavan Gardens'],
    rating: 4.9
  },
  {
    id: '16',
    name: 'Haridwar Ghats',
    city: 'Haridwar',
    state: 'Uttarakhand',
    category: 'Spiritual',
    description: 'Ancient city where the Ganges emerges from the Himalayas, a major pilgrimage site.',
    history: 'Known as "Gateway to God", one of the four sites for the Kumbh Mela.',
    budget: '₹1,500 - ₹4,000',
    latitude: 29.9457,
    longitude: 78.1642,
    images: ['haridwar'],
    nearbyAttractions: ['Mansa Devi Temple', 'Chandi Devi Temple'],
    rating: 4.7
  },
  {
    id: '17',
    name: 'Jim Corbett',
    city: 'Ramnagar',
    state: 'Uttarakhand',
    category: 'Wildlife',
    description: 'India\'s oldest National Park, famous for its Bengal tigers and diverse wildlife.',
    history: 'Established in 1936 as Hailey National Park, later named after conservationist Jim Corbett.',
    budget: '₹6,000 - ₹15,000',
    latitude: 29.53,
    longitude: 78.7747,
    images: ['corbett'],
    nearbyAttractions: ['Garjiya Devi Temple', 'Corbett Museum'],
    rating: 4.8
  },
  {
    id: '18',
    name: 'Andaman Islands',
    city: 'Port Blair',
    state: 'Andaman & Nicobar',
    category: 'Beaches',
    description: 'Pristine white sand beaches, turquoise waters, and world-class scuba diving spots.',
    history: 'Known for historic Cellular Jail and indigenous tribes, now a premier beach destination.',
    budget: '₹30,000 - ₹70,000',
    latitude: 11.6234,
    longitude: 92.7265,
    images: ['andaman'],
    nearbyAttractions: ['Havelock Island', 'Radhanagar Beach', 'Cellular Jail'],
    rating: 4.9
  },
  {
    id: '19',
    name: 'Khajuraho Temples',
    city: 'Khajuraho',
    state: 'Madhya Pradesh',
    category: 'Heritage',
    description: 'A UNESCO site famous for its nagara-style architecture and erotic sculptures.',
    history: 'Built by the Chandela Dynasty between 950 and 1050 CE.',
    budget: '₹3,000 - ₹7,000',
    latitude: 24.8318,
    longitude: 79.9199,
    images: ['khajuraho'],
    nearbyAttractions: ['Panna National Park', 'Raneh Falls'],
    rating: 4.8
  },
  {
    id: '20',
    name: 'Tirupati Temple',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    category: 'Spiritual',
    description: 'The world\'s richest Hindu temple, dedicated to Lord Venkateswara.',
    history: 'Spans over 2000 years with contributions from various dynasties including Cholas and Vijayanagara.',
    budget: '₹2,000 - ₹6,000',
    latitude: 13.6285,
    longitude: 79.4192,
    images: ['tirupati'],
    nearbyAttractions: ['Talakona Waterfall', 'Chandragiri Fort'],
    rating: 4.9
  },
  {
    id: '21',
    name: 'Munnar Tea Gardens',
    city: 'Munnar',
    state: 'Kerala',
    category: 'Nature',
    description: 'Sprawling tea plantations, rolling hills, and misty weather.',
    history: 'Former summer resort for the British Government in South India.',
    budget: '₹5,000 - ₹12,000',
    latitude: 10.0889,
    longitude: 77.0595,
    images: ['munnar'],
    nearbyAttractions: ['Eravikulam National Park', 'Mattupetty Dam'],
    rating: 4.8
  },
  {
    id: '22',
    name: 'Jaisalmer Fort',
    city: 'Jaisalmer',
    state: 'Rajasthan',
    category: 'Heritage',
    description: 'The "Golden Fort" is one of the few "living forts" in the world, built from yellow sandstone.',
    history: 'Built in 1156 AD by Rawal Jaisal from whom it derives its name.',
    budget: '₹4,000 - ₹10,000',
    latitude: 26.9124,
    longitude: 70.9126,
    images: ['jaisalmer-fort'],
    nearbyAttractions: ['Sam Sand Dunes', 'Patwon Ki Haveli'],
    rating: 4.7
  },
  {
    id: '23',
    name: 'Sundarbans',
    city: 'Gosaba',
    state: 'West Bengal',
    category: 'Wildlife',
    description: 'World\'s largest mangrove forest and home to the elusive Royal Bengal Tiger.',
    history: 'A UNESCO World Heritage site and a biosphere reserve.',
    budget: '₹7,000 - ₹15,000',
    latitude: 21.9497,
    longitude: 89.1833,
    images: ['sundarbans'],
    nearbyAttractions: ['Sajnekhali Watch Tower', 'Dobanki Camp'],
    rating: 4.6
  },
  {
    id: '24',
    name: 'Somnath Temple',
    city: 'Somnath',
    state: 'Gujarat',
    category: 'Spiritual',
    description: 'One of the twelve Jyotirlinga shrines of Shiva, located on the western coast.',
    history: 'Known as "The Eternal Shrine", destroyed and rebuilt several times throughout history.',
    budget: '₹2,000 - ₹5,000',
    latitude: 20.888,
    longitude: 70.4012,
    images: ['somnath'],
    nearbyAttractions: ['Triveni Sangam', 'Bhalka Tirth'],
    rating: 4.8
  },
  {
    id: '25',
    name: 'Shimla Ridge',
    city: 'Shimla',
    state: 'Himachal Pradesh',
    category: 'Nature',
    description: 'Classic hill station charm with colonial architecture and mountain views.',
    history: 'Former summer capital of British India.',
    budget: '₹4,000 - ₹12,000',
    latitude: 31.1048,
    longitude: 77.1734,
    images: ['shimla'],
    nearbyAttractions: ['Mall Road', 'Jakhoo Temple', 'Kufri'],
    rating: 4.7
  },
  {
    id: '26',
    name: 'Ellora Caves',
    city: 'Aurangabad',
    state: 'Maharashtra',
    category: 'Heritage',
    description: 'One of the largest rock-cut monastery-temple complexes in the world.',
    history: 'Constructed between 600 and 1000 CE, featuring Buddhist, Hindu, and Jain monuments.',
    budget: '₹3,000 - ₹6,000',
    latitude: 20.0258,
    longitude: 75.178,
    images: ['ellora-caves'],
    nearbyAttractions: ['Ajanta Caves', 'Bibi Ka Maqbara'],
    rating: 4.9
  },
  {
    id: '27',
    name: 'Konark Sun Temple',
    city: 'Konark',
    state: 'Odisha',
    category: 'Heritage',
    description: 'A 13th-century temple designed as a colossal chariot for the Sun God Surya.',
    history: 'Built by King Narasimhadeva I of the Eastern Ganga Dynasty about 1250 CE.',
    budget: '₹2,500 - ₹5,000',
    latitude: 19.8876,
    longitude: 86.0945,
    images: ['konark-temple'],
    nearbyAttractions: ['Chandrabhaga Beach', 'Puri'],
    rating: 4.8
  },
  {
    id: '28',
    name: 'Rani ki Vav',
    city: 'Patan',
    state: 'Gujarat',
    category: 'Heritage',
    description: 'An intricately constructed stepwell that is a UNESCO World Heritage Site.',
    history: 'Built by Queen Udayamati as a memorial to her husband in the 11th century.',
    budget: '₹1,500 - ₹4,000',
    latitude: 23.8584,
    longitude: 72.1022,
    images: ['rani-ki-vav'],
    nearbyAttractions: ['Modhera Sun Temple', 'Sidhpur'],
    rating: 4.7
  },
  {
    id: '29',
    name: 'Charminar',
    city: 'Hyderabad',
    state: 'Telangana',
    category: 'Heritage',
    description: 'A 16th-century mosque and monument that has become a global icon of Hyderabad.',
    history: 'Built in 1591 to celebrate the end of a deadly plague.',
    budget: '₹1,000 - ₹3,000',
    latitude: 17.3616,
    longitude: 78.4747,
    images: ['charminar'],
    nearbyAttractions: ['Golconda Fort', 'Laad Bazaar'],
    rating: 4.7
  },
  {
    id: '30',
    name: 'Kedarnath Temple',
    city: 'Kedarnath',
    state: 'Uttarakhand',
    category: 'Spiritual',
    description: 'One of the holiest Hindu temples dedicated to Shiva in the Himalayas.',
    history: 'Believed to have been originally built by Pandavas and later by Adi Shankaracharya.',
    budget: '₹10,000 - ₹20,000',
    latitude: 30.7352,
    longitude: 79.0669,
    images: ['kedarnath'],
    nearbyAttractions: ['Vasuki Tal', 'Shankaracharya Samadhi'],
    rating: 5.0
  },
  {
    id: '31',
    name: 'Bodh Gaya',
    city: 'Bodh Gaya',
    state: 'Bihar',
    category: 'Spiritual',
    description: 'The place where Gautama Buddha attained enlightenment under the Bodhi tree.',
    history: 'The Mahabodhi Temple complex was built by Emperor Ashoka in the 3rd century BCE.',
    budget: '₹2,000 - ₹5,500',
    latitude: 24.6951,
    longitude: 84.9913,
    images: ['bodhgaya'],
    nearbyAttractions: ['Great Buddha Statue', 'Thai Monastery'],
    rating: 4.8
  },
  {
    id: '32',
    name: 'Vaishno Devi',
    city: 'Katra',
    state: 'Jammu & Kashmir',
    category: 'Spiritual',
    description: 'A holy cave temple dedicated to Vaishno Devi in the Trikuta Mountains.',
    history: 'One of the most visited pilgrimage sites in India.',
    budget: '₹5,000 - ₹12,000',
    latitude: 33.0301,
    longitude: 74.949,
    images: ['vaishno-devi'],
    nearbyAttractions: ['Bhairon Nath Temple', 'Ardh Kuwari'],
    rating: 4.9
  },
  {
    id: '33',
    name: 'Puri Beach',
    city: 'Puri',
    state: 'Odisha',
    category: 'Beaches',
    description: 'A sacred beach famous for its golden sands and the annual Beach Festival.',
    history: 'Associated with the Jagannath Temple, a spiritual beach with high religious value.',
    budget: '₹3,000 - ₹7,000',
    latitude: 19.813,
    longitude: 85.831,
    images: ['puri-beach'],
    nearbyAttractions: ['Jagannath Temple', 'Konark'],
    rating: 4.6
  },
  {
    id: '34',
    name: 'Gokarna Beaches',
    city: 'Gokarna',
    state: 'Karnataka',
    category: 'Beaches',
    description: 'Pristine, less crowded beaches offering a blend of spirituality and relaxation.',
    history: 'Traditional pilgrimage town that became popular for beach lovers.',
    budget: '₹4,000 - ₹9,000',
    latitude: 14.5479,
    longitude: 74.3188,
    images: ['gokarna'],
    nearbyAttractions: ['Mahabaleshwar Temple', 'Murudeshwar'],
    rating: 4.7
  },
  {
    id: '35',
    name: 'Varkala Cliff',
    city: 'Varkala',
    state: 'Kerala',
    category: 'Beaches',
    description: 'Known for unique red laterite cliffs bordering the Arabian Sea.',
    history: 'Mentioned in ancient texts as a place where one can wash away sins.',
    budget: '₹5,000 - ₹11,000',
    latitude: 8.7303,
    longitude: 76.7032,
    images: ['varkala'],
    nearbyAttractions: ['Janardanaswamy Temple', 'Kappil Lake'],
    rating: 4.8
  },
  {
    id: '36',
    name: 'Mahabalipuram',
    city: 'Mahabalipuram',
    state: 'Tamil Nadu',
    category: 'Heritage',
    description: 'UNESCO site famous for its monuments including the Shore Temple.',
    history: 'Built by the Pallava Dynasty in the 7th and 8th centuries.',
    budget: '₹4,000 - ₹9,000',
    latitude: 12.6269,
    longitude: 80.1929,
    images: ['mahabalipuram'],
    nearbyAttractions: ['Arjuna\'s Penance', 'Crocodile Bank'],
    rating: 4.7
  },
  {
    id: '37',
    name: 'Kaziranga Safari',
    city: 'Kanchanjuri',
    state: 'Assam',
    category: 'Wildlife',
    description: 'World-renowned for its population of one-horned rhinos.',
    history: 'A testament to wildlife preservation in the Brahmaputra floodplains.',
    budget: '₹6,000 - ₹14,000',
    latitude: 26.5775,
    longitude: 93.1703,
    images: ['kaziranga-safari'],
    nearbyAttractions: ['Hollongapar Sanctuary', 'Orchid Park'],
    rating: 4.8
  },
  {
    id: '38',
    name: 'Ranthambore Fort',
    city: 'Sawai Madhopur',
    state: 'Rajasthan',
    category: 'Wildlife',
    description: 'A formidable fort situated within the Ranthambore National Park.',
    history: 'The fort dates back to the 10th century and was a key strategic stronghold.',
    budget: '₹5,000 - ₹13,000',
    latitude: 26.0113,
    longitude: 76.4533,
    images: ['ranthambore'],
    nearbyAttractions: ['Padam Talao', 'Jogi Mahal'],
    rating: 4.7
  },
  {
    id: '39',
    name: 'Bandhavgarh',
    city: 'Umaria',
    state: 'Madhya Pradesh',
    category: 'Wildlife',
    description: 'Highest density of Royal Bengal Tigers in the world.',
    history: 'Historically linked to the Ramayana; said to have been given by Lord Rama to Lakshmana.',
    budget: '₹8,000 - ₹18,000',
    latitude: 23.6936,
    longitude: 81.0264,
    images: ['bandhavgarh'],
    nearbyAttractions: ['Bandhavgarh Fort', 'Baghel Museum'],
    rating: 4.9
  },
  {
    id: '40',
    name: 'Gir National Park',
    city: 'Sasan Gir',
    state: 'Gujarat',
    category: 'Wildlife',
    description: 'Only natural habitat of the majestic Asiatic Lion.',
    history: 'Once a private hunting ground, now a successful lion sanctuary.',
    budget: '₹6,000 - ₹12,000',
    latitude: 21.1243,
    longitude: 70.8242,
    images: ['gir'],
    nearbyAttractions: ['Junagadh', 'Somnath'],
    rating: 4.8
  },
  {
    id: '41',
    name: 'Leh City',
    city: 'Leh',
    state: 'Ladakh',
    category: 'Adventure',
    description: 'Capital city of Ladakh, offering moon-like landscapes.',
    history: 'A strategic stopover on the Silk Road for centuries.',
    budget: '₹12,000 - ₹30,000',
    latitude: 34.1526,
    longitude: 77.5771,
    images: ['leh'],
    nearbyAttractions: ['Leh Palace', 'Shanti Stupa'],
    rating: 4.9
  },
  {
    id: '42',
    name: 'Spiti Valley',
    city: 'Kaza',
    state: 'Himachal Pradesh',
    category: 'Adventure',
    description: 'A cold desert mountain valley, famous for ancient monasteries.',
    history: 'Historically part of the Guge kingdom of Tibet.',
    budget: '₹10,000 - ₹25,000',
    latitude: 32.2461,
    longitude: 78.0349,
    images: ['spiti'],
    nearbyAttractions: ['Key Monastery', 'Chandratal Lake'],
    rating: 4.8
  },
  {
    id: '43',
    name: 'Bir Billing',
    city: 'Bir',
    state: 'Himachal Pradesh',
    category: 'Adventure',
    description: 'One of the best paragliding sites in the world.',
    history: 'A Tibetan refugee settlement that evolved into an adventure hub.',
    budget: '₹5,000 - ₹11,000',
    latitude: 32.0514,
    longitude: 76.7161,
    images: ['bir-billing'],
    nearbyAttractions: ['Sherab Ling Monastery', 'Deer Park Institute'],
    rating: 4.7
  },
  {
    id: '44',
    name: 'Cherrapunji',
    city: 'Sohra',
    state: 'Meghalaya',
    category: 'Nature',
    description: 'Famous for living root bridges and massive waterfalls.',
    history: 'Known as the "Scotland of the East" due to its lush green landscape.',
    budget: '₹6,000 - ₹14,000',
    latitude: 25.2702,
    longitude: 91.7323,
    images: ['cherrapunji'],
    nearbyAttractions: ['Nohkalikai Falls', 'Double Decker Root Bridge'],
    rating: 4.8
  },
  {
    id: '45',
    name: 'Darjeeling Hills',
    city: 'Darjeeling',
    state: 'West Bengal',
    category: 'Nature',
    description: 'Famous for its tea industry and the UNESCO-listed Himalayan Railway.',
    history: 'Developed by the British as a sanatorium and hill station.',
    budget: '₹5,000 - ₹15,000',
    latitude: 27.0422,
    longitude: 88.2636,
    images: ['darjeeling'],
    nearbyAttractions: ['Batasia Loop', 'Rock Garden'],
    rating: 4.7
  },
  {
    id: '46',
    name: 'Rann of Kutch',
    city: 'Dhordo',
    state: 'Gujarat',
    category: 'Unique',
    description: 'A massive salt marsh that becomes a white desert in winter.',
    history: 'Known for its vibrant culture and the famous Rann Utsav festival.',
    budget: '₹8,000 - ₹20,000',
    latitude: 23.785,
    longitude: 69.851,
    images: ['kutch'],
    nearbyAttractions: ['Kalo Dungar', 'Mandvi Beach'],
    rating: 4.9
  },
  {
    id: '47',
    name: 'Majuli Island',
    city: 'Majuli',
    state: 'Assam',
    category: 'Unique',
    description: 'The largest river island in the world, a hub of Assamese culture.',
    history: 'Formed by changes in the course of the Brahmaputra river.',
    budget: '₹4,000 - ₹9,000',
    latitude: 26.9602,
    longitude: 94.1802,
    images: ['majuli'],
    nearbyAttractions: ['Jorhat', 'Satra Monasteries'],
    rating: 4.7
  },
  {
    id: '48',
    name: 'Lonar Crater',
    city: 'Lonar',
    state: 'Maharashtra',
    category: 'Unique',
    description: 'The world\'s only salt water lake formed in basaltic rock by a meteor hit.',
    history: 'Estimated over 50,000 years old, geological and ecological interest.',
    budget: '₹2,500 - ₹6,000',
    latitude: 19.976,
    longitude: 76.507,
    images: ['lonar'],
    nearbyAttractions: ['Daitya Sudan Temple', 'Gomukh Temple'],
    rating: 4.6
  },
  {
    id: '49',
    name: 'Victoria Memorial',
    city: 'Kolkata',
    state: 'West Bengal',
    category: 'Heritage',
    description: 'A large marble building, dedicated to memory of Queen Victoria.',
    history: 'Built between 1906 and 1921, magnificent British architecture.',
    budget: '₹500 - ₹2,000',
    latitude: 22.5448,
    longitude: 88.3426,
    images: ['victoria-memorial'],
    nearbyAttractions: ['Princep Ghat', 'Howrah Bridge'],
    rating: 4.7
  },
  {
    id: '50',
    name: 'Udaipur Lakes',
    city: 'Udaipur',
    state: 'Rajasthan',
    category: 'Nature',
    description: 'The "City of Lakes" is known for beautiful palaces and lakes.',
    history: 'Founded by Maharana Udai Singh II in 1559.',
    budget: '₹6,000 - ₹18,000',
    latitude: 24.5854,
    longitude: 73.7125,
    images: ['udaipur'],
    nearbyAttractions: ['City Palace', 'Jag Mandir'],
    rating: 4.9
  },
  {
    id: '51',
    name: 'Chitrakote Falls',
    city: 'Jagdalpur',
    state: 'Chhattisgarh',
    category: 'Nature',
    description: 'Often called the "Niagara of India", a massive horseshoe waterfall on the Indravati River.',
    history: 'Sacred and scenic site, mentioned in local tribal folklore.',
    budget: '₹3,000 - ₹7,000',
    latitude: 19.1437,
    longitude: 81.6961,
    images: ['chitrakote'],
    nearbyAttractions: ['Kanger Valley National Park', 'Kutumsar Caves', 'Jagdalpur Palace'],
    rating: 4.9
  },
  {
    id: '52',
    name: 'Mainpat (Mini Tibet)',
    city: 'Mainpat',
    state: 'Chhattisgarh',
    category: 'Nature',
    description: 'A beautiful plateau known as the "Shimla of Chhattisgarh" and home to a Tibetan settlement.',
    history: 'Tibetan community settled here in 1962, creating a unique cultural blend.',
    budget: '₹4,000 - ₹10,000',
    latitude: 22.8123,
    longitude: 83.2845,
    images: ['mainpat'],
    nearbyAttractions: ['Tiger Point Waterfall', 'Fish Point', 'Buddhist Monasteries'],
    rating: 4.8
  }
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected for seeding");

    await Place.deleteMany();
    console.log("🗑️ Cleared existing places");

    const placesToInsert = destinations.map(dest => ({
      name: dest.name,
      city: dest.city,
      state: dest.state,
      shortDescription: dest.description.substring(0, 150) + '...',
      fullDescription: dest.description,
      category: [dest.category],
      images: dest.images.map(imgKey => imageMap[imgKey] || 'https://images.unsplash.com/photo-1564507592333-c60657eea523'),
      isTopPlace: dest.rating >= 4.8,
      travelInfo: {
        budget: dest.budget
      },
      location: {
        lat: dest.latitude,
        lng: dest.longitude
      },
      history: dest.history,
      nearbyAttractions: dest.nearbyAttractions,
      tags: [dest.category, dest.state]
    }));

    await Place.insertMany(placesToInsert);
    console.log(`🎉 Seeded ${placesToInsert.length} places successfully!`);

    process.exit(0);
  } catch (err) {
    console.error("❌ Seeding failed:", err);
    process.exit(1);
  }
};

seedDB();
